### ISSUE TITLE
New glyphs?

### ISSUE THREAD

**Issue by slipsec** [thekewe/ingress-slack-emoji#3]
This is one of our favorite things ever, we love it & want more!

**Comment by thekewe** [comment]
That's wonderful to hear! Thank you for the reminder. The new glyphs are in the works.

**Comment by thekewe** [comment]
The new glyphs are live! I _think_ I got them all. If you happen to catch any missing glyphs please let me know. ;)

**Comment by pwiecz** [comment]
Hi, I went through the glyph listed in glyphtionary.com and ingress.wikia.com/wiki/Glyphs
I've found several missing glyphs. 
But I think I haven't encountered any of them in wild, except possibly "Share".
Here's the list:
- consequence
- creativity
- live again/reincarnate
- presence
- persue chase
- share
- sustain
- sustain all
- worth
