### ISSUE TITLE
One glyph missing

### ISSUE THREAD

**Issue by pwiecz** [thekewe/ingress-slack-emoji#7]
As I cannot reopen the old issue, I'm creating a new one.
There is at least one glyph missing - SHARE.
It's not occurring in any sequences as far as I know, but I have definitely encountered it several times while hacking level-1 portals.
It looks like this: http://glyphtionary.com/glyphs/thumbs/Share.png

**Comment by thekewe** [comment]
Fixed! I don't recall seeing this myself so I'll take your word on it. Thank you so much for the info! <3

![glyph_share_emoji](https://cloud.githubusercontent.com/assets/82804/26515546/b417b1f4-4230-11e7-9be4-c193d1833195.png)
